# Generated by Django 3.1.2 on 2021-09-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'grado',
                'verbose_name_plural': 'grados',
            },
        ),
        migrations.CreateModel(
            name='Gran_oriente',
            fields=[
                ('id_gran_oriente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gran_oriente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'gran_oriente',
                'verbose_name_plural': 'gran_orientes',
            },
        ),
        migrations.CreateModel(
            name='Logia',
            fields=[
                ('id_logia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_logia', models.CharField(max_length=50)),
                ('nro_logia', models.IntegerField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudad')),
                ('gran_oriente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gran_oriente')),
            ],
            options={
                'verbose_name': 'logia',
                'verbose_name_plural': 'logias',
            },
        ),
        migrations.CreateModel(
            name='Oriente',
            fields=[
                ('id_oriente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_oriente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'oriente',
                'verbose_name_plural': 'orientes',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Rito',
            fields=[
                ('id_rito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rito', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'rito',
                'verbose_name_plural': 'ritos',
            },
        ),
        migrations.CreateModel(
            name='Valle',
            fields=[
                ('id_valle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_valle', models.CharField(max_length=50)),
                ('oriente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.oriente')),
            ],
            options={
                'verbose_name': 'valle',
                'verbose_name_plural': 'valles',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('login_usuario', models.CharField(max_length=15)),
                ('password_usuario', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('ncelular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_grado', models.DateField()),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grado')),
                ('logia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.logia')),
            ],
        ),
        migrations.AddField(
            model_name='logia',
            name='rito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rito'),
        ),
        migrations.AddField(
            model_name='logia',
            name='valle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.valle'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pais'),
        ),
    ]
