# Generated by Django 3.1.2 on 2021-09-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('editorial', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'editorial',
                'verbose_name_plural': 'editoriales',
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id_formato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'formato',
                'verbose_name_plural': 'formatos',
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id_fuente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fuente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'fuente',
                'verbose_name_plural': 'fuentes',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'grado',
                'verbose_name_plural': 'grados',
            },
        ),
        migrations.CreateModel(
            name='Origen_Descarga',
            fields=[
                ('id_origen', models.AutoField(primary_key=True, serialize=False)),
                ('origen_descarga', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'origen descarga',
                'verbose_name_plural': 'origen descargas',
            },
        ),
        migrations.CreateModel(
            name='Pais_Ciudad',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='SubClase',
            fields=[
                ('id_subclase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subclase', models.CharField(max_length=50)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.clase')),
            ],
            options={
                'verbose_name': 'subclase',
                'verbose_name_plural': 'subclases',
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_libro', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=30)),
                ('anho_edicion', models.DateField()),
                ('fecha_alta_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=100)),
                ('libro_fuente', models.FileField(blank=True, null=True, upload_to='libro_fuente/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.editorial')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.formato')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.fuente')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.grado')),
                ('origen_descarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.origen_descarga')),
                ('pais_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.pais_ciudad')),
                ('subclase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.subclase')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.tipo')),
            ],
        ),
    ]
